const C=require('./common.cjs');const {fs,path,out,write,append,base}=C;
const {chromium}=require(process.env.AUDIT_PLAYWRIGHT_PATH||'C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const executablePath=process.env.AUDIT_CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe';
const ua='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36';
const mobileUa='Mozilla/5.0 (Linux; Android 14; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36';
function instrumentation(){window.__audit={lcp:0,cls:0,longTasks:[],events:[],stalls:[],usefulAt:null,splashPresent:false};
 const a=window.__audit;for(const type of ['largest-contentful-paint','layout-shift','longtask','event'])try{new PerformanceObserver(list=>{for(const e of list.getEntries()){if(type==='largest-contentful-paint'){a.lcp=e.startTime;a.lcpElement=e.element?.tagName+' '+e.element?.textContent?.slice(0,100);}if(type==='layout-shift'&&!e.hadRecentInput)a.cls+=e.value;if(type==='longtask')a.longTasks.push({start:e.startTime,duration:e.duration});if(type==='event')a.events.push({name:e.name,start:e.startTime,duration:e.duration,interactionId:e.interactionId});}}).observe({type,buffered:true,durationThreshold:16});}catch{}
 let previous=performance.now();function frame(){const now=performance.now();if(now-previous>50)a.stalls.push({start:previous,duration:now-previous});previous=now;const splash=document.getElementById('splash-screen-root');if(splash&&getComputedStyle(splash).display!=='none'&&getComputedStyle(splash).opacity!=='0')a.splashPresent=true;const h=document.querySelector('h1');if(!a.usefulAt&&h&&(!splash||getComputedStyle(splash).display==='none')){const r=h.getBoundingClientRect();if(r.height>0&&r.top<innerHeight&&getComputedStyle(h).opacity!=='0'){a.usefulAt=now;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
}
async function capture(page,cdp,label){await page.waitForLoadState('load',{timeout:45000});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(1000);const m=await cdp.send('Performance.getMetrics');const data=await page.evaluate(()=>{const n=performance.getEntriesByType('navigation')[0];return{...window.__audit,navigation:n?.toJSON(),paint:performance.getEntriesByType('paint').map(x=>x.toJSON()),resources:performance.getEntriesByType('resource').map(x=>x.toJSON()),userAgent:navigator.userAgent,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,splashSession:sessionStorage.getItem('ryma_splash_v6')}});return{label,...data,cdpMetrics:Object.fromEntries(m.metrics.map(x=>[x.name,x.value]))};}
async function main(){const browser=await chromium.launch({headless:true,executablePath,args:['--no-first-run','--disable-default-apps']});write('browser-environment.json',{version:browser.version(),executablePath,headless:true,ordinaryVisitor:'Normal Chrome UA supplied and no reduced motion; verifies normal splash branch, not Lighthouse bypass',network:{normal:'Loopback, no artificial throttle',constrained:{latencyMs:150,downloadBytesPerSecond:200000,uploadBytesPerSecond:93750}},cache:'New context + Network.clearBrowserCache for first; same-page reload retains disk cache and sessionStorage; separate cold return clears cache only',cpu:'CDP Emulation.setCPUThrottlingRate; 1 or 4',sampleSize:5,observation:'Record primary actionability immediately; then await document load and font readiness plus 1s before collecting paint, execution and resource metrics. No networkidle.'});
const profiles=[{name:'desktop-normal',mobile:false,cpu:1,network:false},{name:'mobile-normal',mobile:true,cpu:1,network:false},{name:'mobile-constrained',mobile:true,cpu:1,network:true},{name:'mobile-constrained-cpu4',mobile:true,cpu:4,network:true},{name:'headless-control',mobile:false,cpu:1,network:false,bot:true},{name:'reduced-motion-control',mobile:false,cpu:1,network:false,reduce:true}];
const summary=[];
try{for(const profile of profiles){for(let i=0;i<5;i++){
 const context=await browser.newContext({viewport:profile.mobile?{width:390,height:844}:{width:1440,height:900},isMobile:profile.mobile,hasTouch:profile.mobile,deviceScaleFactor:profile.mobile?2:1,userAgent:profile.bot?undefined:profile.mobile?mobileUa:ua,reducedMotion:profile.reduce?'reduce':'no-preference',locale:'en-GB',timezoneId:'Europe/Lisbon',...(i===0?{recordHar:{path:path.join(out,`${profile.name}.har`),mode:'full',content:'omit'}}:{})});
 await context.addInitScript(instrumentation);if(i===0)await context.tracing.start({screenshots:true,snapshots:true,sources:false});
 const page=await context.newPage();page.setDefaultTimeout(45000);const errors=[],failed=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()?.errorText}));const cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');await cdp.send('Network.enable');await cdp.send('Network.clearBrowserCache');await cdp.send('Emulation.setCPUThrottlingRate',{rate:profile.cpu});if(profile.network)await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750,connectionType:'cellular3g'});
 for(const visit of ['first-cold','return-warm',...(i===0?['return-cold']:[])]){
  if(visit==='return-cold')await cdp.send('Network.clearBrowserCache');const start=performance.now();if(visit==='first-cold')await page.goto(base,{waitUntil:'domcontentloaded'});else await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('#splash-screen-root').waitFor({state:'hidden',timeout:45000});
  const action=page.locator('a[href="/rendez-vous"]').filter({visible:true}).first();await action.click({trial:true});const usable=await page.evaluate(()=>performance.now());const record=await capture(page,cdp,`${profile.name}-${i}-${visit}`);record.primaryUsableMs=usable;record.wallMs=performance.now()-start;record.profile=profile;record.repeat=i;record.visit=visit;record.consoleErrors=[...errors];record.failedRequests=[...failed];summary.push(record);append('browser-samples.jsonl',record);if(i===0)await page.screenshot({path:path.join(out,`${profile.name}-${visit}.png`),fullPage:false});console.log(JSON.stringify({label:record.label,lcp:record.lcp,cls:record.cls,useful:record.usefulAt,usable:record.primaryUsableMs,js:record.resources.filter(r=>/\.js(?:\?|$)/.test(r.name)).reduce((s,r)=>s+r.encodedBodySize,0)}));
 }
 if(i===0)await context.tracing.stop({path:path.join(out,`${profile.name}-trace.zip`)});await context.close();
}}}finally{await browser.close();write('browser-summary.json',summary.map(r=>({label:r.label,profile:r.profile,visit:r.visit,repeat:r.repeat,ttfb:r.navigation?.responseStart,fcp:r.paint.find(x=>x.name==='first-contentful-paint')?.startTime,lcp:r.lcp,cls:r.cls,usefulAt:r.usefulAt,primaryUsableMs:r.primaryUsableMs,splashPresent:r.splashPresent,longTasks:r.longTasks.length,blockingMs:r.longTasks.reduce((s,t)=>s+Math.max(0,t.duration-50),0),maxLongTask:Math.max(0,...r.longTasks.map(x=>x.duration)),jsEncodedBytes:r.resources.filter(x=>/\.js(?:\?|$)/.test(x.name)).reduce((s,x)=>s+x.encodedBodySize,0),jsTransferBytes:r.resources.filter(x=>/\.js(?:\?|$)/.test(x.name)).reduce((s,x)=>s+x.transferSize,0),scriptDurationSeconds:r.cdpMetrics.ScriptDuration,errors:r.consoleErrors.length,failedRequests:r.failedRequests.length})))}
}
if(require.main===module)main().catch(e=>{console.error(e);write('browser-fatal.json',{error:e.stack});process.exitCode=1});
module.exports={chromium,executablePath,ua,instrumentation,capture};
