const C=require('./common.cjs');const crypto=require('node:crypto');
const d=C.db();d.pragma('foreign_keys=ON');const baseline=JSON.parse(C.fs.readFileSync(C.path.join(C.out,'baseline-records.json')));const tables=d.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(r=>r.name);const manifest={runId:C.runId,database:C.secret.env.DATABASE_PATH,capturedAt:new Date().toISOString(),tables:{}};
for(const t of tables){const known=new Set(baseline[t]||[]);manifest.tables[t]=d.prepare(`SELECT rowid AS auditRowid,* FROM ${t}`).all().filter(r=>!known.has(r.auditRowid)).map(r=>({rowid:r.auditRowid,...(r.id?{id:r.id}:{}),...(r.phone?{phone:r.phone}:{}),...(r.key?{key:r.key}:{}),...(r.sessionId?{sessionId:r.sessionId}:{})}));}
C.write('synthetic-record-manifest.json',manifest);
const beforeIntegrity={foreignKeys:d.pragma('foreign_key_check'),quickCheck:d.pragma('quick_check'),duplicateActiveSlots:d.prepare("SELECT date,startTime,count(*) n FROM appointments WHERE status!='CANCELLED' GROUP BY date,startTime HAVING n>1").all()};
const order=['patient_sessions','invoices','prescriptions','appointments','patients',...tables.filter(t=>!['patient_sessions','invoices','prescriptions','appointments','patients'].includes(t))];const deleted={};d.transaction(()=>{for(const t of order){const stmt=d.prepare(`DELETE FROM ${t} WHERE rowid=?`);deleted[t]=0;for(const r of manifest.tables[t])deleted[t]+=stmt.run(r.rowid).changes;}})();const after=Object.fromEntries(tables.map(t=>[t,d.prepare(`SELECT COUNT(*) n FROM ${t}`).get().n]));const remaining=Object.fromEntries(tables.map(t=>[t,manifest.tables[t].filter(r=>d.prepare(`SELECT 1 FROM ${t} WHERE rowid=?`).get(r.rowid)).length]));d.pragma('wal_checkpoint(TRUNCATE)');const afterIntegrity=d.pragma('foreign_key_check');d.close();
const env=JSON.parse(C.fs.readFileSync(C.path.join(C.out,'environment.json')));const sourceChanges=env.files.filter(f=>{const p=C.path.join(C.root,f.file);return!C.fs.existsSync(p)||crypto.createHash('sha256').update(C.fs.readFileSync(p)).digest('hex')!==f.sha256;}).map(f=>f.file);
C.write('cleanup-verification.json',{time:new Date().toISOString(),database:manifest.database,beforeIntegrity,deleted,after,remaining,afterIntegrity,applicationSourceChanges:sourceChanges,passed:Object.values(remaining).every(v=>v===0)&&Object.entries(after).every(([t,n])=>n===(baseline[t]||[]).length)&&beforeIntegrity.foreignKeys.length===0&&beforeIntegrity.duplicateActiveSlots.length===0&&beforeIntegrity.quickCheck.every(r=>Object.values(r).every(v=>v==='ok'))&&afterIntegrity.length===0&&sourceChanges.length===0});
console.log(JSON.stringify({deleted,after,remaining,sourceChanges},null,2));
