const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const c=JSON.parse(fs.readFileSync(path.join(__dirname,'latest.json')));
const secret=JSON.parse(fs.readFileSync(path.join(c.out,'private-config.json')));
const Database=require(path.join(c.root,'node_modules/better-sqlite3'));
const base='http://localhost:3217';
if(!secret.env.DATABASE_PATH.startsWith(c.out+path.sep)||secret.env.TURSO_DATABASE_URL)throw Error('Isolation check failed');
const write=(name,value)=>fs.writeFileSync(path.join(c.out,name),JSON.stringify(value,null,2));
const append=(name,value)=>fs.appendFileSync(path.join(c.out,name),JSON.stringify(value)+'\n');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function db(){return new Database(secret.env.DATABASE_PATH,{fileMustExist:true,timeout:5000});}
const times=['08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','14:00','14:30','15:00','15:30','16:00','16:30','17:00'];
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Lisbon',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function dateOffset(offset){const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10);}
function slot(index,days=7){let dayOffset=days;let remain=Math.floor(index/times.length);while(true){const date=dateOffset(dayOffset);if(new Date(date+'T12:00Z').getUTCDay()!==0){if(remain--===0)return {date,startTime:times[index%times.length]};}dayOffset++;}}
function historicalSlot(index){let offset=-1,remain=Math.floor(index/times.length);while(true){const date=dateOffset(offset);if(new Date(date+'T12:00Z').getUTCDay()!==0){if(remain--===0)return{date,startTime:times[index%times.length]};}offset--;}}
function phone(i){return '+3519'+String(20000000+i).padStart(8,'0');}
function payload(index,slotIndex=index){return{patientName:`AUDIT ${c.runId} ${index}`,phone:phone(100000+index),service:'reeducation-posturale',...slot(slotIndex),notes:c.runId,lang:'en',_hp_company:'',_form_rendered_at:Date.now()-5000};}
async function req(url,opts={}){const start=performance.now();try{const response=await fetch(base+url,{...opts,redirect:'manual',signal:AbortSignal.timeout(opts.timeout||15000),headers:{'content-type':'application/json',origin:base,...opts.headers}});const text=await response.text();let json;try{json=JSON.parse(text)}catch{}return{status:response.status,ms:performance.now()-start,bytes:Buffer.byteLength(text),json,text,headers:Object.fromEntries(response.headers)};}catch(e){return{status:0,ms:performance.now()-start,bytes:0,error:e.name+': '+e.message};}}
async function login(ip='198.18.0.1',owner=false){const r=await req('/api/admin/login',{method:'POST',body:JSON.stringify({password:secret.password}),headers:{'x-forwarded-for':ip}});if(r.status!==200||!r.json?.success||!r.headers['set-cookie'])throw Error('Login failed '+JSON.stringify(r));let cookie=r.headers['set-cookie'].split(';')[0];if(owner){const o=await req('/api/admin/analytics/verify',{method:'POST',headers:{cookie,'x-forwarded-for':ip},body:JSON.stringify({password:secret.ownerPassword})});if(o.status!==200||!o.headers['set-cookie'])throw Error('Owner login failed '+JSON.stringify(o));cookie=o.headers['set-cookie'].split(';')[0];}return{cookie,ms:r.ms};}
function stats(rows,elapsed){const a=rows.map(r=>r.ms).sort((x,y)=>x-y);const p=q=>a.length?a[Math.max(0,Math.ceil(q*a.length)-1)]:null;return{n:a.length,p50:p(.5),p90:a.length>=50?p(.9):null,p95:a.length>=100?p(.95):null,p99:a.length>=1000?p(.99):null,min:a[0],max:a.at(-1),mean:a.reduce((a,b)=>a+b,0)/a.length,elapsedSeconds:elapsed/1000,rps:rows.length/(elapsed/1000),businessRps:rows.filter(r=>r.ok).length/(elapsed/1000),successes:rows.filter(r=>r.ok).length,unexpected:rows.filter(r=>!r.ok&&r.status!==429&&r.status!==409).length,throttled:rows.filter(r=>r.status===429).length,conflicts:rows.filter(r=>r.status===409).length,timeouts:rows.filter(r=>!r.status).length,meanBytes:rows.reduce((s,r)=>s+r.bytes,0)/rows.length};}
function seed(target){const d=db();d.pragma('foreign_keys=ON');const before=d.prepare('SELECT COUNT(*) n FROM patients').get().n;const p=d.prepare('INSERT INTO patients(id,patientName,phone,email,pathologyTags,medicalHistory,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?)');const a=d.prepare('INSERT INTO appointments(id,patientName,phone,service,date,startTime,status,notes,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?)');const s=d.prepare('INSERT INTO patient_sessions(id,patientId,date,time,serviceSlug,notes,createdAt) VALUES(?,?,?,?,?,?,?)');const inv=d.prepare('INSERT INTO invoices(id,invoiceNumber,appointmentId,patientId,patientName,patientPhone,serviceSlug,serviceName,amount,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?,?)');
const start=performance.now();d.transaction(()=>{for(let i=before;i<target;i++){const id=`${c.runId}-patient-${i}`,name=`AUDIT Patient ${String(i).padStart(5,'0')}`,at=historicalSlot(i),ts=at.date+'T12:00:00.000Z';p.run(id,name,phone(i),`patient${i}@example.invalid`,'posture','Synthetic audit record',ts,ts);a.run(`${c.runId}-appointment-${i}`,name,phone(i),'reeducation-posturale',at.date,at.startTime,'COMPLETED',c.runId,ts,ts);for(let j=0;j<3;j++)s.run(`${c.runId}-session-${i}-${j}`,id,at.date,at.startTime,'reeducation-posturale','Synthetic session '+j,ts);inv.run(`${c.runId}-invoice-${i}`,`AUDIT-${i}`,`${c.runId}-appointment-${i}`,id,name,phone(i),'reeducation-posturale','Reeducation posturale',45,ts,ts);}})();const tables=['patients','appointments','patient_sessions','invoices'];const counts=Object.fromEntries(tables.map(t=>[t,d.prepare(`SELECT COUNT(*) n FROM ${t}`).get().n]));append('dataset-manifests.jsonl',{time:new Date().toISOString(),target,counts,seedMs:performance.now()-start,foreignKeyCheck:d.pragma('foreign_key_check'),databasePath:secret.env.DATABASE_PATH,ids:{prefix:c.runId,patients:'patient-{0..N-1}',appointments:'appointment-{0..N-1}',sessions:'session-{0..N-1}-{0..2}',invoices:'invoice-{0..N-1}'}});d.close();return counts;}
module.exports={...c,secret,fs,path,os,base,write,append,sleep,db,times,today,dateOffset,slot,historicalSlot,phone,payload,req,login,stats,seed};
