const C=require('./common.cjs');const {req,db,login,payload,write,append,stats,runId}=C;
async function main(){const {cookie}=await login('198.18.4.1');const outcomes={};
const contested=payload(50000,500);const start=performance.now();const attempts=await Promise.all(Array.from({length:50},(_,i)=>req('/api/appointments',{method:'POST',headers:{'x-forwarded-for':`198.18.4.${i+10}`,'idempotency-key':`${runId}-contested-${i}`},body:JSON.stringify({...contested,patientName:`AUDIT Contested ${i}`,phone:C.phone(250000+i)})})));const d=db();const count=d.prepare("SELECT COUNT(*) n FROM appointments WHERE date=? AND startTime=? AND status!='CANCELLED'").get(contested.date,contested.startTime).n;outcomes.contested={target:contested,counts:Object.fromEntries([...new Set(attempts.map(r=>r.status))].map(s=>[s,attempts.filter(r=>r.status===s).length])),records:count,passed:count===1&&attempts.filter(r=>r.status===201&&r.json?.success).length===1&&attempts.filter(r=>r.status===409&&r.json?.error==='slot_taken').length===49,samples:attempts.map(r=>({ms:r.ms,status:r.status,response:r.json})),elapsedMs:performance.now()-start};d.close();
const unique=await Promise.all(Array.from({length:10},(_,i)=>{const b=payload(51000+i,510+i);return req('/api/appointments',{method:'POST',headers:{'x-forwarded-for':`198.18.5.${i+1}`},body:JSON.stringify(b)}).then(r=>({body:b,...r}));}));const v=db();outcomes.distinct={samples:unique.map(r=>({ms:r.ms,status:r.status,persisted:v.prepare('SELECT COUNT(*) n FROM appointments WHERE phone=? AND date=? AND startTime=?').get(r.body.phone,r.body.date,r.body.startTime).n})),passed:unique.every(r=>r.status===201&&v.prepare('SELECT COUNT(*) n FROM appointments WHERE phone=?').get(r.body.phone).n===1)};v.close();
const retryBody=payload(52000,520),key=runId+'-retry';const first=await req('/api/appointments',{method:'POST',headers:{'x-forwarded-for':'198.18.5.50','idempotency-key':key},body:JSON.stringify(retryBody)});const retry=await req('/api/appointments',{method:'POST',headers:{'x-forwarded-for':'198.18.5.50','idempotency-key':key},body:JSON.stringify(retryBody)});const rd=db();const retryRows=rd.prepare('SELECT * FROM appointments WHERE phone=?').all(retryBody.phone);rd.close();outcomes.retry={first:{status:first.status,json:first.json},second:{status:retry.status,json:retry.json,cache:retry.headers?.['x-cache-lookup']},records:retryRows.length,passed:first.status===201&&retry.status===201&&retryRows.length===1&&retry.headers['x-cache-lookup']==='HIT_IDEMPOTENT'};
const cancel=await req('/api/admin/appointments/'+retryRows[0].id,{method:'PATCH',headers:{cookie},body:JSON.stringify({status:'CANCELLED'})});const availability=await req('/api/slots?date='+retryBody.date);outcomes.availabilityAfterCancel={status:cancel.status,available:availability.json?.slots?.find(s=>s.time===retryBody.startTime)?.available,passed:cancel.status===200&&availability.json?.slots?.find(s=>s.time===retryBody.startTime)?.available===true};
// Check preservation of independent fields under simultaneous PATCHes.
const id=runId+'-appointment-1';const updates=await Promise.all([req('/api/admin/appointments/'+id,{method:'PATCH',headers:{cookie},body:JSON.stringify({notes:runId+' concurrent note'})}),req('/api/admin/appointments/'+id,{method:'PATCH',headers:{cookie},body:JSON.stringify({status:'CONFIRMED'})})]);const ud=db();const updated=ud.prepare('SELECT status,notes FROM appointments WHERE id=?').get(id);outcomes.independentUpdates={responses:updates.map(r=>r.status),persisted:updated,passed:updated?.status==='CONFIRMED'&&updated?.notes===runId+' concurrent note'};ud.close();
// Phone-rate limit exercise: three distinct valid successes then one real 429.
const rate=[];for(let i=0;i<4;i++){const b={...payload(53000,530+i),phone:C.phone(353000)};const r=await req('/api/appointments',{method:'POST',headers:{'x-forwarded-for':'198.18.5.60'},body:JSON.stringify(b)});rate.push({status:r.status,json:r.json,ms:r.ms});}outcomes.phoneRateLimit={samples:rate,passed:rate.slice(0,3).every(r=>r.status===201)&&rate[3].status===429};
const integrity=db();outcomes.integrity={duplicates:integrity.prepare("SELECT date,startTime,count(*) n FROM appointments WHERE status!='CANCELLED' GROUP BY date,startTime HAVING n>1").all(),foreignKeys:integrity.pragma('foreign_key_check'),quickCheck:integrity.pragma('quick_check')};integrity.close();write('concurrency.json',outcomes);console.log(JSON.stringify(outcomes,null,2));if(Object.values(outcomes).some(v=>v.passed===false)||outcomes.integrity.duplicates.length||outcomes.integrity.foreignKeys.length)throw Error('Concurrency correctness failure');}
main().catch(e=>{console.error(e);write('concurrency-fatal.json',{error:e.stack});process.exitCode=1});
