const C=require('./common.cjs');const B=require('./browser.cjs');
const {base,out,path,write,append,db,runId}=C;
async function measure(page,name,action,done){const t=performance.now();await action();if(done)await done();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const row={name,ms:performance.now()-t,time:new Date().toISOString(),ok:true};append('journey-samples.jsonl',row);console.log(JSON.stringify(row));return row;}
async function main(){const browser=await B.chromium.launch({headless:true,executablePath:B.executablePath});const errors=[];const context=await browser.newContext({viewport:{width:1440,height:900},userAgent:B.ua,timezoneId:'Europe/Lisbon',locale:'en-GB'});await context.addCookies([{name:'ryma_lang',value:'en',url:base}]);await context.addInitScript(()=>localStorage.setItem('ryma_lang','en'));await context.addInitScript(B.instrumentation);await context.tracing.start({screenshots:true,snapshots:true});const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
async function scenario(name,fn){if(!['navigation','public-booking'].includes(name))return;try{await fn();}catch(e){process.exitCode=1;append('journey-failures.jsonl',{name,error:e.message});await page.screenshot({path:path.join(out,`journey-failed-${name}.png`)});console.log('FAILED '+name+': '+e.message)}}
try{
 await scenario('navigation',async()=>{await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#splash-screen-root').waitFor({state:'hidden'});
 for(let i=0;i<5;i++){await measure(page,'navigate-services',()=>page.locator('a[href="/services"]').filter({visible:true}).first().click(),()=>page.waitForURL('**/services'));await page.getByRole('heading',{level:1}).waitFor();await measure(page,'navigate-service-detail',()=>page.locator('a[href="/services/reeducation-posturale"]').filter({visible:true}).first().click(),()=>page.waitForURL('**/services/reeducation-posturale'));await page.getByRole('heading',{level:1}).waitFor();await measure(page,'navigate-pricing',()=>page.locator('a[href="/tarifs"]').filter({visible:true}).first().click(),()=>page.waitForURL('**/tarifs'));await page.getByRole('heading',{level:1}).waitFor();}
 await page.screenshot({path:path.join(out,'journey-pricing.png')});});
 await scenario('language',async()=>{await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#splash-screen-root').waitFor({state:'hidden'});await measure(page,'language-en-to-fr',async()=>{await page.getByRole('button',{name:/Selected language/}).click();await page.getByRole('button',{name:/Français/}).click();},()=>page.waitForFunction(()=>document.documentElement.lang==='fr'));await page.screenshot({path:path.join(out,'journey-language-fr.png')});await context.addCookies([{name:'ryma_lang',value:'en',url:base}]);await page.evaluate(()=>localStorage.setItem('ryma_lang','en'));});
 await scenario('body-viewer',async()=>{await page.goto(base+'/services',{waitUntil:'domcontentloaded'});await page.getByRole('group',{name:'Body view'}).scrollIntoViewIfNeeded();await measure(page,'body-view-back',()=>page.getByRole('group',{name:'Body view'}).getByRole('button').last().click());const canvas=page.locator('canvas').first();if(await canvas.count()){const b=await canvas.boundingBox();const t=performance.now();await page.mouse.move(b.x+b.width*.4,b.y+b.height*.5);await page.mouse.down();await page.mouse.move(b.x+b.width*.7,b.y+b.height*.5,{steps:20});await page.mouse.up();await page.waitForTimeout(500);append('journey-samples.jsonl',{name:'3d-drag',ms:performance.now()-t,ok:true,note:'Includes scripted 20-step drag and 500ms observation; not click latency'});}await page.screenshot({path:path.join(out,'journey-body-viewer.png')});write('viewer-observation.json',await page.evaluate(()=>({canvases:document.querySelectorAll('canvas').length,webgl:!!document.createElement('canvas').getContext('webgl2'),longTasks:window.__audit.longTasks,events:window.__audit.events,stalls:window.__audit.stalls})));});
 // Complete real form submission with a future Lisbon opening day; database verification included.
 await scenario('public-booking',async()=>{const workflow=performance.now();await measure(page,'open-booking',()=>page.goto(base+'/rendez-vous',{waitUntil:'domcontentloaded'}),()=>page.locator('#service-reeducation-posturale').waitFor());await page.locator('#splash-screen-root').waitFor({state:'hidden'});await measure(page,'choose-service',()=>page.locator('#service-reeducation-posturale').click(),()=>page.getByRole('heading',{name:'2. Pick a Date'}).waitFor());await measure(page,'change-service',async()=>{await page.getByRole('button',{name:'Change',exact:true}).click();await page.locator('#service-massage-therapeutique').click();},()=>page.getByRole('heading',{name:'2. Pick a Date'}).waitFor());
 const date=C.slot(0,1).date;const day=Number(date.slice(-2));const todayMonth=C.today.slice(0,7);if(date.slice(0,7)!==todayMonth){const label=new Date(C.today+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric'});await page.getByText(label,{exact:true}).locator('..').locator('button').last().click();}
 await measure(page,'choose-date-load-availability',()=>page.getByRole('button',{name:String(day),exact:true}).click(),()=>page.getByRole('button',{name:'Next',exact:true}).waitFor({state:'visible'}));await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('heading',{name:'3. Choose Time Slot'}).waitFor();await measure(page,'choose-time',()=>page.getByRole('button',{name:'14:00',exact:true}).click());await measure(page,'change-time',()=>page.getByRole('button',{name:'14:30',exact:true}).click());await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByPlaceholder('Your full name').fill('AUDIT Browser '+runId);await page.locator('input[type="tel"]').fill(C.phone(490000));const submitStart=performance.now();const response=page.waitForResponse(r=>r.url().endsWith('/api/appointments')&&r.request().method()==='POST');await page.locator('button[type="submit"]').click();const r=await response;if(r.status()!==201)throw Error('Booking returned '+r.status()+' '+await r.text());await page.getByText('Appointment Confirmed!',{exact:true}).waitFor();const d=db();const persisted=d.prepare('SELECT id,date,startTime,service FROM appointments WHERE phone=?').all(C.phone(490000));d.close();if(persisted.length!==1||persisted[0].date!==date||persisted[0].startTime!=='14:30'||persisted[0].service!=='massage-therapeutique')throw Error('Booking DB mismatch');append('journey-samples.jsonl',{name:'public-booking-submit-to-persisted-visible',ms:performance.now()-submitStart,ok:true,persisted});append('journey-samples.jsonl',{name:'public-booking-complete-workflow',ms:performance.now()-workflow,ok:true,note:'Includes scripted filling and clicks; excludes human think time'});await page.screenshot({path:path.join(out,'journey-booking-confirmed.png')});});
 await scenario('admin',async()=>{await page.goto(base+'/admin/login',{waitUntil:'domcontentloaded'});await page.locator('input[type="password"]').fill(C.secret.password);await measure(page,'admin-login-to-dashboard',()=>page.locator('button[type="submit"]').click(),async()=>{await page.waitForURL('**/admin');await page.getByPlaceholder('Search patient, phone, service...').waitFor();});await page.waitForTimeout(1200);await page.screenshot({path:path.join(out,'journey-dashboard.png')});write('admin-dom.txt.json',{text:(await page.locator('body').innerText()).slice(0,25000),buttons:await page.getByRole('button').allTextContents()});
 await measure(page,'admin-filter-appointments',()=>page.getByPlaceholder('Search patient, phone, service...').fill('AUDIT Patient 00001'),()=>page.getByText('AUDIT Patient 00001',{exact:true}).first().waitFor());
 await measure(page,'admin-tab-patients',()=>page.getByRole('button',{name:/Patient Records/}).first().click(),()=>page.getByPlaceholder('Search patient, phone...').waitFor());await measure(page,'admin-search-patient',()=>page.getByPlaceholder('Search patient, phone...').fill('AUDIT Patient 00001'),()=>page.getByText('AUDIT Patient 00001',{exact:true}).first().waitFor());await measure(page,'admin-open-patient-sessions',()=>page.getByText('AUDIT Patient 00001',{exact:true}).first().click(),()=>page.getByText('Synthetic session 0',{exact:false}).first().waitFor());await page.screenshot({path:path.join(out,'journey-patient-record.png')});
 await measure(page,'admin-tab-invoices',()=>page.getByRole('button',{name:/Invoicing & Receipts/}).first().click(),()=>page.getByText('AUDIT-0',{exact:true}).first().waitFor());
 await measure(page,'admin-open-analytics',()=>page.getByRole('button',{name:/Analytics & Reports/}).first().click(),()=>page.locator('input[type="password"]').waitFor());await page.locator('input[type="password"]').fill(C.secret.ownerPassword);await measure(page,'admin-unlock-analytics',()=>page.locator('form').filter({has:page.locator('input[type="password"]')}).locator('button[type="submit"]').click(),()=>page.locator('input[type="password"]').waitFor({state:'hidden'}));await page.screenshot({path:path.join(out,'journey-analytics.png')});
 });
}finally{write('journey-errors.json',errors);await context.tracing.stop({path:path.join(out,'journeys-trace.zip')});await context.close();await browser.close();}}
main().catch(e=>{console.error(e);write('journeys-fatal.json',{error:e.stack});process.exitCode=1});
