'use client';
import { useTeamServices } from '@/components/ServiceCatalogProvider';

import { useState } from 'react';
import { IconArrowUpRight, IconCalendar, IconCalendarOff, IconChevronLeft, IconChevronRight, IconClock, IconDoor, IconEdit, IconPlus, IconSearch, IconStethoscope, IconTrash, IconUsers } from '@tabler/icons-react';
import { getLocalizedText } from '@/data/services';
import type { Lang } from '@/lib/i18n';
import { practitionerIntervals } from '@/lib/schedule-math';
import { formatMinute, type SchedulingConfiguration } from '@/types/scheduling';
import { DAYS, copyFor, dayName, EmptyState, hoursLabel, iconButton, initials, inputClass, localeFor, panelClass, primaryButton, secondaryButton, totalMinutes } from './team-ui';
import type { EditorKind } from './TeamEditors';

interface ViewProps {config: SchedulingConfiguration; lang: Lang; open: (kind: EditorKind, id?: string) => void}
export const lisbonToday = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Lisbon',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateLabel = (date: string, lang: Lang, options: Intl.DateTimeFormatOptions = {day:'numeric',month:'short'}) => new Intl.DateTimeFormat(localeFor(lang), {...options,timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));

export function TeamRoster({config,lang,open}: ViewProps) {
  const txt = copyFor(lang), [search,setSearch] = useState(''), [filter,setFilter] = useState('all');
  const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase();
  const filtered = config.practitioners.filter(p => (filter === 'all' || (filter === 'active' ? !!p.active : !p.active)) && normalize(p.name+' '+p.profession).includes(normalize(search.trim())));
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-3 @min-[620px]:flex-row @min-[620px]:items-center"><div><h3 className="text-base font-semibold tracking-tight text-slate-900">{txt('A sua equipa','Your team','Votre équipe', "Su equipo")}</h3><p className="mt-1 text-xs text-slate-500">{txt('Pessoas, especialidades e horários, sempre organizados.','People, specialities and schedules, all in order.','Praticiens, spécialités et horaires, bien organisés.', "Personas, especialidades y horarios, todo en orden.")}</p></div><div className="flex gap-2 @min-[620px]:max-w-md @min-[620px]:flex-1 @min-[620px]:justify-end"><div className="relative min-w-0 flex-1 @min-[620px]:max-w-60"><IconSearch size={17} className="pointer-events-none absolute left-3 top-3.5 text-slate-400"/><input className={inputClass+' pl-10!'} value={search} onChange={e => setSearch(e.target.value)} aria-label={txt('Pesquisar equipa','Search team','Rechercher dans l’équipe', "Buscar equipo")} placeholder={txt('Pesquisar equipa…','Search team…','Rechercher…', "Buscar equipo…")}/></div><select className={inputClass+' w-auto! max-w-[45%]'} aria-label={txt('Filtrar profissionais','Filter practitioners','Filtrer les praticiens', "Filtrar profesionales")} value={filter} onChange={e => setFilter(e.target.value)}><option value="all">{txt('Todos','All','Tous', "Todos")}</option><option value="active">{txt('Ativos','Active','Actifs', "Activo")}</option><option value="archived">{txt('Arquivados','Archived','Archivés', "Archivado")}</option></select></div></div>
    {filtered.length ? <div className="grid gap-4 @min-[560px]:grid-cols-2 @min-[900px]:grid-cols-3">{filtered.map(p => {
      const services = config.services.filter(s => s.practitionerId === p.id), hours = config.hours.filter(h => h.practitionerId === p.id);
      const published=services.some(s=>config.treatments?.some(t=>t.slug===s.service&&t.status==='PUBLISHED'));
      const ready = published && hours.length > 0, online = !!p.active && !!p.bookable && ready && published;
      const badge = !p.active ? txt('Arquivado','Archived','Archivé', "Archivado") : !ready ? txt('Por configurar','Setup needed','À configurer', "Configuración pendiente") : online ? txt('Online','Online','En ligne', "En línea") : txt('Só na clínica','Clinic only','En clinique', "Solo en la clínica");
      return <article key={p.id} className={panelClass+' group flex flex-col overflow-hidden transition-shadow hover:shadow-md'}>
        <div className="flex-1 p-5"><div className="flex items-start justify-between gap-2"><div className="flex size-12 shrink-0 items-center justify-center rounded-2xl text-base font-semibold ring-1 ring-inset ring-black/5" style={{background:p.color+'12',color:p.color}}>{initials(p.name)}</div><span className={'inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold '+(!p.active ? 'bg-slate-100 text-slate-500' : !ready ? 'bg-amber-50 text-amber-700' : online ? 'bg-emerald-50 text-emerald-700' : 'bg-blue-50 text-blue-600')}><span className="size-1.5 rounded-full bg-current"/>{badge}</span></div>
          <h4 className="mt-4 break-words text-base font-semibold tracking-tight text-slate-900">{p.name}</h4><p className="mt-1 break-words text-sm text-slate-500">{p.profession}</p>
          <div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><IconStethoscope size={15} className="text-slate-400"/><strong className="font-semibold text-slate-700">{services.length}</strong> {services.length === 1 ? txt('tratamento','treatment','soin', "tratamiento") : txt('tratamentos','treatments','soins', "tratamientos")}</span><span className="inline-flex items-center gap-1.5"><IconClock size={15} className="text-slate-400"/><strong className="font-semibold text-slate-700">{hoursLabel(totalMinutes(hours))}</strong> / {txt('semana','week','semaine', "semana")}</span></div>
          <div className="mt-4 flex gap-1.5" aria-label={txt('Dias de trabalho semanais','Weekly working days','Jours de travail hebdomadaires', "Días laborables semanales")}>{DAYS.map(day => <span key={day} title={dayName(day,lang)} className={'flex h-7 min-w-0 flex-1 items-center justify-center rounded-md text-[10px] font-medium capitalize '+(hours.some(h => h.dayOfWeek === day) && p.active ? 'bg-blue-50 text-blue-700' : 'bg-slate-50 text-slate-300')}>{dayName(day,lang,true).slice(0,3)}</span>)}</div>
        </div><button type="button" onClick={() => open('practitioner',p.id)} className="flex min-h-12 w-full items-center justify-between border-t border-slate-100 bg-slate-50/40 px-5 text-xs font-semibold text-slate-600 transition-colors hover:bg-blue-50 hover:text-blue-700 focus-visible:outline-2 focus-visible:outline-blue-500" aria-label={`${txt('Gerir perfil','Manage profile','Gérer le profil', "Gestionar perfil")} · ${p.name}`}>{txt('Gerir perfil','Manage profile','Gérer le profil', "Gestionar perfil")}<IconArrowUpRight size={17}/></button>
      </article>;
    })}{!search && filter !== 'archived' && <button type="button" onClick={() => open('practitioner')} className="flex min-h-44 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white/40 p-5 text-center transition-colors hover:border-blue-400 hover:bg-blue-50/30 focus-visible:outline-2 focus-visible:outline-blue-500"><span className="mb-3 flex size-11 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-400"><IconPlus size={20}/></span><span className="text-sm font-semibold text-slate-700">{txt('Expandir a equipa','Grow your team','Agrandir l’équipe', "Amplíe su equipo")}</span><span className="mt-1.5 max-w-48 text-xs leading-relaxed text-slate-400">{txt('Adicione um profissional e personalize o seu horário.','Add a practitioner and tailor their schedule.','Ajoutez un praticien et personnalisez ses horaires.', "Añada un profesional y adapte su horario.")}</span></button>}</div> : <div className={panelClass}><EmptyState icon={<IconUsers size={23}/>} title={txt('Nenhum profissional encontrado','No practitioners found','Aucun praticien trouvé', "No se han encontrado profesionales")} description={search || filter !== 'all' ? txt('Experimente outro nome ou filtro.','Try another name or filter.','Essayez un autre nom ou filtre.', "Pruebe otro nombre o filtro.") : txt('Comece por adicionar o primeiro membro da equipa.','Start by adding your first team member.','Commencez par ajouter un membre à votre équipe.', "Empiece añadiendo al primer miembro del equipo.")} action={search || filter !== 'all' ? <button className={secondaryButton} onClick={() => {setSearch('');setFilter('all');}}>{txt('Limpar filtros','Clear filters','Effacer les filtres', "Borrar filtros")}</button> : <button className={primaryButton} onClick={() => open('practitioner')}><IconPlus size={16}/>{txt('Adicionar profissional','Add practitioner','Ajouter un praticien', "Añadir profesional")}</button>}/></div>}
    <WeeklyOverview config={config} lang={lang}/>
  </div>;
}

function WeeklyOverview({config,lang}: Omit<ViewProps,'open'>) {
  const txt = copyFor(lang), [offset,setOffset] = useState(0), today = lisbonToday();
  const base = new Date(today+'T12:00:00Z');
  base.setUTCDate(base.getUTCDate() - (base.getUTCDay()+6)%7 + offset*7);
  const dates = Array.from({length:7}, (_,i) => {const d = new Date(base);d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10);});
  const practitioners = config.practitioners.filter(p => p.active);
  return <section className={panelClass+' overflow-hidden'} aria-label={txt('Vista semanal da equipa','Weekly team overview','Vue hebdomadaire de l’équipe', "Resumen semanal del equipo")}>
    <div className="flex flex-wrap items-center justify-between gap-4 p-4 sm:p-5"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-slate-50 text-slate-400"><IconCalendar size={20}/></div><div><h3 className="text-sm font-semibold text-slate-800">{txt('A semana da equipa','The team’s week','La semaine de l’équipe', "La semana del equipo")}</h3><p className="mt-1 text-xs text-slate-500">{dateLabel(dates[0],lang)} — {dateLabel(dates[6],lang,{day:'numeric',month:'short',year:'numeric'})}</p></div></div><div className="flex items-center gap-1 rounded-xl border border-slate-200 p-0.5"><button className={iconButton} onClick={() => setOffset(offset-1)} aria-label={txt('Semana anterior','Previous week','Semaine précédente', "Semana anterior")}><IconChevronLeft size={17}/></button><button className="min-h-10 rounded-lg px-3 text-xs font-semibold text-slate-600 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-blue-500" onClick={() => setOffset(0)}>{txt('Esta semana','This week','Cette semaine', "Esta semana")}</button><button className={iconButton} onClick={() => setOffset(offset+1)} aria-label={txt('Próxima semana','Next week','Semaine suivante', "Semana siguiente")}><IconChevronRight size={17}/></button></div></div>
    {practitioners.length ? <div className="overflow-x-auto border-y border-slate-100" tabIndex={0} role="region" aria-label={txt('Horários semanais; deslize para ver todos os dias','Weekly hours; scroll to see every day','Horaires hebdomadaires ; faites défiler pour voir tous les jours', "Horario semanal; desplácese para ver todos los días")}><table className="w-full min-w-[720px] table-fixed border-collapse text-xs"><thead><tr className="bg-slate-50/70"><th className="w-40 px-5 py-3 text-left font-medium text-slate-400">{txt('Profissional','Practitioner','Praticien', "Profesional")}</th>{dates.map(date => <th key={date} className={'px-1 py-3 text-center font-medium '+(date === today ? 'bg-blue-50/60 text-blue-600' : 'text-slate-400')} scope="col"><span className="block capitalize">{dateLabel(date,lang,{weekday:'short'}).replace('.','')}</span><span className={'mx-auto mt-1 flex size-6 items-center justify-center rounded-full '+(date === today ? 'bg-blue-600 font-semibold text-white' : 'text-slate-600')}>{date.slice(-2)}</span></th>)}</tr></thead><tbody>{practitioners.map(p => <tr key={p.id} className="border-t border-slate-100"><th scope="row" className="px-5 py-4 text-left"><span className="flex items-center gap-2"><span className="size-1.5 shrink-0 rounded-full" style={{background:p.color}}/><span className="truncate font-medium text-slate-700" title={p.name}>{p.name}</span></span></th>{dates.map(date => {const intervals = practitionerIntervals(config,p.id,date);return <td key={date} className={'px-1.5 py-3 text-center tabular-nums '+(date === today ? 'bg-blue-50/25' : '')}>{intervals.length ? <div className="space-y-1">{intervals.map(([start,end],i) => <span key={i} className="block whitespace-nowrap rounded-md bg-blue-50/80 px-1 py-1.5 text-[10px] font-medium text-blue-700">{formatMinute(start)}–{formatMinute(end)}</span>)}</div> : <span className="text-slate-300" aria-label={txt('Indisponível','Unavailable','Indisponible', "No disponible")}>—</span>}</td>;})}</tr>)}</tbody></table></div> : <p className="border-t border-slate-100 px-5 py-8 text-sm text-slate-500">{txt('Ative um profissional para ver o horário semanal.','Activate a practitioner to see weekly hours.','Activez un praticien pour voir ses horaires hebdomadaires.', "Active un profesional para ver el horario semanal.")}</p>}
    <p className="px-4 py-3 text-[11px] leading-relaxed text-slate-400 sm:px-5">{txt('Horários configurados, incluindo exceções e limites da clínica. Esta vista não desconta as marcações existentes. Horário de Lisboa.','Configured hours, including exceptions and clinic limits. This view does not subtract existing bookings. Lisbon time.','Horaires configurés, avec exceptions et limites de la clinique. Cette vue ne déduit pas les rendez-vous existants. Heure de Lisbonne.', "Horarios configurados, incluidas las excepciones y los límites de la clínica. Esta vista no descuenta las reservas existentes. Hora de Lisboa.")}</p>
  </section>;
}

export function ClinicOverview({config,lang,open}: ViewProps) {
  const txt = copyFor(lang), hours = config.hours.filter(h => h.practitionerId === '*');
  return <section className={panelClass+' overflow-hidden'}><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5 sm:p-6"><div><h3 className="text-base font-semibold text-slate-900">{txt('Horário da clínica','Clinic opening hours','Horaires de la clinique', "Horario de apertura de la clínica")}</h3><p className="mt-1 text-sm text-slate-500">{hoursLabel(totalMinutes(hours))} / {txt('semana · Horário de Lisboa','week · Lisbon time','semaine · Heure de Lisbonne', "semana · hora de Lisboa")}</p></div><button className={secondaryButton} onClick={() => open('clinic')}><IconEdit size={16}/>{txt('Editar horário','Edit hours','Modifier les horaires', "Editar horarios")}</button></div><div className="divide-y divide-slate-100 px-5 sm:px-6">{DAYS.map(day => {const intervals = hours.filter(h => h.dayOfWeek === day).sort((a,b) => a.startMinute-b.startMinute);return <div key={day} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="flex items-center gap-3"><span className={'size-1.5 rounded-full '+(intervals.length ? 'bg-emerald-400' : 'bg-slate-300')}/><span className="text-sm font-medium capitalize text-slate-700">{dayName(day,lang)}</span></div><div className="flex flex-wrap gap-2">{intervals.length ? intervals.map((h,i) => <span key={i} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs tabular-nums text-slate-600">{formatMinute(h.startMinute)} — {formatMinute(h.endMinute)}</span>) : <span className="text-xs text-slate-400">{txt('Fechado','Closed','Fermé', "Cerrado")}</span>}</div></div>;})}</div><div className="flex items-start gap-2.5 border-t border-blue-100 bg-blue-50/50 p-5 text-xs leading-relaxed text-blue-800"><IconClock size={17} className="shrink-0"/>{txt('A disponibilidade online combina este horário com o de cada profissional. Use «Ausências» para feriados e alterações pontuais.','Online availability combines these hours with each practitioner’s schedule. Use “Leave” for holidays and one-off changes.','Les disponibilités en ligne combinent ces heures avec celles de chaque praticien. Utilisez « Absences » pour les jours fériés et changements ponctuels.', "La disponibilidad en línea combina estos horarios con la agenda de cada profesional. Use «Ausencias» para vacaciones y cambios puntuales.")}</div></section>;
}

export function ExceptionsOverview({config,lang,open}: ViewProps) {
  const txt = copyFor(lang), [period,setPeriod] = useState('upcoming'), [scope,setScope] = useState('all'), today = lisbonToday();
  const exceptions = config.exceptions.filter(e => (scope === 'all' || e.practitionerId === scope) && (period === 'upcoming' ? e.date >= today : e.date < today)).sort((a,b) => (period === 'upcoming' ? 1 : -1)*(a.date.localeCompare(b.date) || a.startMinute-b.startMinute));
  return <section className={panelClass+' overflow-hidden'}><div className="flex flex-wrap items-center justify-between gap-4 p-5 sm:p-6"><div><h3 className="text-base font-semibold text-slate-900">{txt('Ausências e exceções','Leave & exceptions','Absences et exceptions', "Ausencias y excepciones")}</h3><p className="mt-1 text-xs text-slate-500">{txt('Planeie férias, feriados e horários especiais.','Plan leave, holidays and replacement hours.','Planifiez congés, jours fériés et horaires exceptionnels.', "Planifique ausencias, vacaciones y horarios sustitutorios.")}</p></div><button className={primaryButton} onClick={() => open('exception')}><IconPlus size={16}/>{txt('Nova exceção','New exception','Nouvelle exception', "Nueva excepción")}</button></div><div className="flex flex-wrap gap-2 border-y border-slate-100 bg-slate-50/50 px-5 py-3 sm:px-6"><select className={inputClass+' flex-1 sm:w-auto! sm:flex-none'} aria-label={txt('Período das exceções','Exception period','Période des exceptions', "Periodo de excepciones")} value={period} onChange={e => setPeriod(e.target.value)}><option value="upcoming">{txt('Próximas','Upcoming','À venir', "Próximas")}</option><option value="past">{txt('Passadas','Past','Passées', "Pasado")}</option></select><select className={inputClass+' flex-1 sm:w-auto! sm:max-w-xs sm:flex-none'} aria-label={txt('Filtrar por profissional','Filter by practitioner','Filtrer par praticien', "Filtrar por profesional")} value={scope} onChange={e => setScope(e.target.value)}><option value="all">{txt('Toda a equipa','All team members','Toute l’équipe', "Todo el equipo")}</option><option value="*">{txt('Clínica','Clinic','Clinique', "Clínica")}</option>{config.practitioners.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
    {exceptions.length ? <ul className="divide-y divide-slate-100">{exceptions.map(e => <li key={e.id} className="flex items-start gap-3 p-4 sm:gap-4 sm:px-6 sm:py-5"><div className="w-12 shrink-0 overflow-hidden rounded-xl border border-slate-200 text-center"><span className="block bg-slate-50 py-1 text-[10px] font-medium uppercase text-slate-400">{dateLabel(e.date,lang,{month:'short'})}</span><span className="block py-1.5 text-lg font-semibold leading-none text-slate-700">{e.date.slice(-2)}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="break-words text-sm font-semibold text-slate-800">{e.label || (e.kind === 'closed' ? txt('Indisponível','Unavailable','Indisponible', "No disponible") : txt('Horário especial','Replacement hours','Horaires exceptionnels', "Horario sustitutorio"))}</h4><span className={'rounded-md px-2 py-0.5 text-[10px] font-medium '+(e.kind === 'closed' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700')}>{e.kind === 'closed' ? txt('Ausência','Leave','Absence', "Ausencias") : txt('Horário especial','Special hours','Horaires spéciaux', "Horario especial")}</span></div><p className="mt-1.5 break-words text-xs text-slate-500">{config.practitioners.find(p => p.id === e.practitionerId)?.name || txt('Toda a clínica','Whole clinic','Toute la clinique', "Toda la clínica")}</p><p className="mt-1 text-xs tabular-nums text-slate-400">{dateLabel(e.date,lang,{day:'numeric',month:'short',year:'numeric'})} · {e.startMinute === 0 && e.endMinute === 1440 ? txt('Dia inteiro','All day','Toute la journée', "Todo el día") : `${formatMinute(e.startMinute)}–${formatMinute(e.endMinute)}`}</p></div><div className="flex shrink-0 flex-col sm:flex-row"><button className={iconButton} aria-label={`${txt('Editar exceção','Edit exception','Modifier l’exception', "Editar excepción")} · ${e.label || e.date}`} onClick={() => open('exception',e.id)}><IconEdit size={17}/></button><button className={iconButton+' hover:text-rose-600!'} aria-label={`${txt('Remover exceção','Remove exception','Supprimer l’exception', "Eliminar excepción")} · ${e.label || e.date}`} onClick={() => open('delete-exception',e.id)}><IconTrash size={17}/></button></div></li>)}</ul> : <EmptyState icon={<IconCalendarOff size={23}/>} title={txt('Tudo em ordem','All clear','Tout est en ordre', "Todo en orden")} description={txt('Não há exceções para este período e filtro. Os horários semanais aplicam-se normalmente.','No exceptions match this period and filter. Regular weekly hours apply.','Aucune exception pour cette période et ce filtre. Les horaires hebdomadaires habituels s’appliquent.', "Ninguna excepción coincide con este periodo y filtro. Se aplica el horario semanal habitual.")}/>}
  </section>;
}

export function ResourcesOverview({config,lang,open}: ViewProps) {
  const TEAM_SERVICES = useTeamServices();
  const txt = copyFor(lang);
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="text-base font-semibold text-slate-900">{txt('Salas e equipamentos','Rooms & equipment','Salles et équipements', "Salas y equipos")}</h3><p className="mt-1 text-xs text-slate-500">{txt('Recursos partilhados sem sobreposição de marcações.','Shared resources without overlapping bookings.','Des ressources partagées sans chevauchement de réservations.', "Recursos compartidos sin reservas solapadas.")}</p></div><button className={primaryButton} onClick={() => open('resource')}><IconPlus size={16}/>{txt('Adicionar recurso','Add resource','Ajouter une ressource', "Añadir recurso")}</button></div>
    {config.resources.length ? <div className="grid gap-4 @min-[560px]:grid-cols-2 @min-[900px]:grid-cols-3">{config.resources.map(r => {const services = config.serviceResources.filter(s => s.resourceId === r.id);return <article key={r.id} className={panelClass+' flex flex-col overflow-hidden'}><div className="flex-1 p-5"><div className="flex items-center justify-between gap-3"><div className="flex size-11 items-center justify-center rounded-xl bg-violet-50 text-violet-500"><IconDoor size={22}/></div><span className={'rounded-full px-2.5 py-1 text-[10px] font-semibold '+(r.active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500')}>{r.active ? txt('Ativo','Active','Actif', "Activo") : txt('Inativo','Inactive','Inactif', "Inactivo")}</span></div><h4 className="mt-4 break-words font-semibold text-slate-800">{r.name}</h4><p className="mt-1 text-xs text-slate-400">{txt('1 unidade · Reserva exclusiva por tratamento','1 unit · Exclusive reservation per treatment','1 unité · Réservation exclusive par soin', "1 unidad · Reserva exclusiva por tratamiento")}</p><div className="mt-4 flex flex-wrap gap-1.5">{services.length ? services.map(s => <span key={s.service} className="rounded-md border border-slate-100 bg-slate-50 px-2 py-1 text-[10px] leading-relaxed text-slate-500">{getLocalizedText(TEAM_SERVICES.find(t => t.slug === s.service)?.name || {
    es: s.service,pt:s.service,en:s.service,fr:s.service},lang)}</span>) : <p className="text-xs text-amber-600">{txt('Sem tratamentos associados','No linked treatments','Aucun soin associé', "Sin tratamientos vinculados")}</p>}</div></div><button className="flex min-h-12 items-center justify-between border-t border-slate-100 bg-slate-50/40 px-5 text-xs font-semibold text-slate-600 hover:bg-blue-50 hover:text-blue-700 focus-visible:outline-2 focus-visible:outline-blue-500" aria-label={`${txt('Gerir recurso','Manage resource','Gérer la ressource', "Gestionar recurso")} · ${r.name}`} onClick={() => open('resource',r.id)}>{txt('Gerir recurso','Manage resource','Gérer la ressource', "Gestionar recurso")}<IconArrowUpRight size={17}/></button></article>;})}</div> : <div className={panelClass}><EmptyState icon={<IconDoor size={24}/>} title={txt('Espaço para cuidar melhor','Room for better care','De l’espace pour mieux soigner', "Espacio para una mejor atención")} description={txt('Adicione salas ou equipamentos partilhados. O sistema impede que sejam reservados por dois tratamentos ao mesmo tempo.','Add shared rooms or equipment. The system prevents them from being reserved for two treatments at the same time.','Ajoutez des salles ou équipements partagés. Le système empêche leur réservation simultanée pour deux soins.', "Añada salas o equipos compartidos. El sistema impide reservarlos para dos tratamientos al mismo tiempo.")} action={<button className={secondaryButton} onClick={() => open('resource')}><IconPlus size={16}/>{txt('Criar primeiro recurso','Create first resource','Créer une première ressource', "Crear primer recurso")}</button>}/></div>}
  </div>;
}
