'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { IconPlus, IconRefresh, IconStethoscope, IconSearch, IconEdit, IconExternalLink, IconUsers, IconClock } from '@tabler/icons-react';
import { getLocalizedText } from '@/data/services';
import type { Lang } from '@/lib/i18n';
import type { SchedulingConfiguration } from '@/types/scheduling';
import type { Treatment, TreatmentStatus } from '@/types/treatments';
import { copyFor, EditorDialog, Field, inputClass, panelClass, primaryButton, secondaryButton, type SaveFailure } from './team/team-ui';

async function loadCatalog():Promise<SchedulingConfiguration> {
  const r=await fetch('/api/admin/treatments',{cache:'no-store'});
  if(!r.ok)throw new Error('Unable to load treatments. Please retry.');
  return r.json();
}
export function TreatmentsTab({lang}: {lang:Lang}) {
  const txt=copyFor(lang);
  const [config,setConfig]=useState<SchedulingConfiguration|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [query,setQuery]=useState(''),[filter,setFilter]=useState<'ALL'|TreatmentStatus>('ALL'),[loading,setLoading]=useState(true);
  const [editor,setEditor]=useState<{config:SchedulingConfiguration;treatment?:Treatment;generation?:number}|null>(null);
  const refresh=useCallback(async()=>{
    setLoading(true);setError('');
    try {const data=await loadCatalog();setConfig(data);return data;}
    catch(e){setError((e as Error).message);throw e;}
    finally {setLoading(false);}
  },[]);
  useEffect(()=>{void refresh().catch(()=>{});},[refresh]);
  const statuses={DRAFT:txt('Rascunho','Draft','Brouillon', "Borrador"),PUBLISHED:txt('Publicado','Published','Publié', "Publicado"),ARCHIVED:txt('Arquivado','Archived','Archivé', "Archivado")};
  const treatments=config?.treatments??[];
  const visible=treatments.filter(t=>(filter==='ALL'||t.status===filter)&&`${getLocalizedText(t.name,lang)} ${t.slug}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  return <div className="@container min-w-0 space-y-6 text-slate-800">
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">{txt('Gestão da clínica','Clinic management','Gestion de la clinique', "Gestión de la clínica")}</p><h2 className="text-2xl font-semibold tracking-tight">{txt('Tratamentos','Treatments','Soins', "Tratamientos")}</h2><p className="mt-2 max-w-xl text-sm text-slate-500">{txt('Um catálogo para o site, as marcações e a sua equipa.','One catalogue for your website, bookings and team.','Un catalogue pour le site, les réservations et votre équipe.', "Un catálogo para su sitio web, reservas y equipo.")}</p></div>
      <div className="flex gap-2"><button className={secondaryButton} aria-label={txt('Atualizar catálogo','Refresh catalogue','Actualiser le catalogue', "Actualizar catálogo")} disabled={loading} onClick={()=>void refresh().catch(()=>{})}><IconRefresh size={18} className={loading?'animate-spin':''}/></button><button className={primaryButton} disabled={!config||loading} onClick={()=>config&&setEditor({config})}><IconPlus size={18}/>{txt('Novo tratamento','New treatment','Nouveau soin', "Nuevo tratamiento")}</button></div>
    </header>
    {error&&<p role="alert" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">{error}</p>}
    {notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
    <div className="grid grid-cols-3 gap-3">{(['PUBLISHED','DRAFT','ARCHIVED'] as const).map(status=><button key={status} onClick={()=>setFilter(filter===status?'ALL':status)} aria-pressed={filter===status} className={panelClass+' p-4 text-left '+(filter===status?'ring-2 ring-blue-500':'')}><span className="text-xs text-slate-500">{statuses[status]}</span><span className="mt-2 block text-2xl font-semibold tabular-nums">{treatments.filter(t=>t.status===status).length}</span></button>)}</div>
    <div className="flex flex-wrap gap-3"><label className="relative min-w-0 flex-1"><IconSearch size={17} className="absolute left-3 top-3.5 text-slate-400"/><input className={inputClass+' pl-10'} aria-label={txt('Pesquisar tratamentos','Search treatments','Rechercher un soin', "Buscar tratamientos")} placeholder={txt('Pesquisar tratamentos…','Search treatments…','Rechercher un soin…', "Buscar tratamientos…")} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label={txt('Estado','Status','Statut', "Estado")} className={inputClass+' w-auto!'} value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="ALL">{txt('Todos os estados','All statuses','Tous les statuts', "Todos los estados")}</option>{Object.entries(statuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
    <div className="grid gap-4 @min-[620px]:grid-cols-2 @min-[1000px]:grid-cols-3">
      {visible.map(t=>{
        const assigned=config!.services.filter(s=>s.service===t.slug),overrides=assigned.filter(s=>s.durationMinutes!==null).length;
        return <article key={t.slug} className={panelClass+' flex flex-col overflow-hidden'}>
          <div className="flex-1 p-5"><div className="flex items-start justify-between gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><IconStethoscope size={22}/></span><span className={'rounded-full px-2.5 py-1 text-[11px] font-semibold '+(t.status==='PUBLISHED'?'bg-emerald-50 text-emerald-700':t.status==='DRAFT'?'bg-amber-50 text-amber-800':'bg-slate-100 text-slate-500')}>{statuses[t.status]}</span></div>
            <h3 className="mt-4 break-words text-base font-semibold">{getLocalizedText(t.name,lang)}</h3><p className="mt-2 line-clamp-2 text-sm leading-relaxed text-slate-500">{getLocalizedText(t.shortDesc,lang)}</p>
            <div className="mt-5 flex flex-wrap items-center gap-4 text-sm"><strong>{new Intl.NumberFormat(lang,{style:'currency',currency:'EUR'}).format(t.price)}</strong><span className="flex items-center gap-1.5 text-slate-500"><IconClock size={15}/>{t.duration}</span><span className="flex items-center gap-1.5 text-slate-500"><IconUsers size={15}/>{assigned.length}</span></div>
            {overrides>0&&<p className="mt-2 text-xs text-slate-400">{txt('Durações personalizadas na Equipa: ','Custom durations in Team: ','Durées personnalisées dans Équipe : ', "Duraciones personalizadas en Equipo: ")}{overrides}</p>}
          </div>
          <div className="flex border-t border-slate-100 bg-slate-50/40"><button className="flex min-h-12 flex-1 items-center justify-center gap-2 text-xs font-semibold hover:bg-blue-50 hover:text-blue-700" onClick={()=>setEditor({config:config!,treatment:t})} aria-label={`${txt('Editar','Edit','Modifier', "Editar")} ${getLocalizedText(t.name,lang)}`}><IconEdit size={15}/>{txt('Gerir tratamento','Manage treatment','Gérer le soin', "Gestionar tratamiento")}</button>{t.status==='PUBLISHED'&&<a href={`/services/${t.slug}`} target="_blank" rel="noopener noreferrer" className="flex min-h-12 items-center gap-2 border-l border-slate-100 px-4 text-xs hover:bg-blue-50" aria-label={`${txt('Ver no site','View on website','Voir sur le site', "Ver en el sitio web")} · ${getLocalizedText(t.name,lang)}`}><IconExternalLink size={16}/></a>}</div>
        </article>;
      })}
    </div>
    {!visible.length&&<p role="status" className={panelClass+' p-10 text-center text-sm text-slate-500'}>{loading?txt('A carregar…','Loading…','Chargement…', "Cargando…"):txt('Nenhum tratamento encontrado.','No treatments found.','Aucun soin trouvé.', "No se han encontrado tratamientos.")}</p>}
    <p className="text-xs leading-relaxed text-slate-400">{txt('Arquivar impede novas marcações. As consultas, os registos clínicos e as faturas existentes são preservados.','Archiving prevents new bookings. Existing appointments, clinical records and invoices are preserved.','L’archivage empêche de nouvelles réservations. Les rendez-vous, dossiers cliniques et factures existants sont conservés.', "Al archivar se impiden nuevas reservas. Se conservan las citas, historias clínicas y facturas existentes.")}</p>
    {editor&&<TreatmentEditor key={`${editor.treatment?.slug??'new'}-${editor.config.revision}-${editor.generation??0}`} {...editor} lang={lang} onClose={()=>setEditor(null)} onReload={async()=>{const config=await refresh();setEditor({config,treatment:config.treatments?.find(t=>t.slug===editor.treatment?.slug),generation:(editor.generation??0)+1});}} onSaved={async()=>{
      setEditor(null);setNotice(txt('Tratamento guardado. O catálogo e as marcações foram atualizados.','Treatment saved. The catalogue and bookings have been updated.','Soin enregistré. Le catalogue et les réservations ont été mis à jour.', "Tratamiento guardado. El catálogo y las reservas se han actualizado."));
      window.dispatchEvent(new Event('ryma_catalogue_changed'));window.dispatchEvent(new Event('ryma_schedule_changed'));
      await refresh().catch(()=>{});
    }}/>}
  </div>;
}
function TreatmentEditor({config,treatment,lang,onClose,onReload,onSaved}: {config:SchedulingConfiguration;treatment?:Treatment;lang:Lang;onClose:()=>void;onReload:()=>Promise<void>;onSaved:()=>Promise<void>}) {
  const txt=copyFor(lang),lock=useRef(false);
  const initial={slug:treatment?.slug??'',pole:treatment?.pole??'kinesitherapie',status:treatment?.status??'DRAFT',name:treatment?.name??{fr:''},shortDesc:treatment?.shortDesc??{fr:''},longDesc:treatment?.longDesc??{fr:''},careGoals:treatment?.careGoals??[],bodyZones:treatment?.bodyZones??[],sessionFlow:treatment?.sessionFlow??{fr:[]},indications:treatment?.indications??{fr:[]},contraindications:treatment?.contraindications??{fr:[]},faq:treatment?.faq??[],keywords:(treatment?.keywords??[]).join('\n'),duration:String(treatment?.durationMinutes??30),price:(treatment?.price??0).toFixed(2),practitionerIds:config.services.filter(s=>s.service===treatment?.slug).map(s=>s.practitionerId)};
  const [draft,setDraft]=useState(initial),[language,setLanguage]=useState<Lang>(lang);
  const [busy,setBusy]=useState(false),[failure,setFailure]=useState<SaveFailure|null>(null);
  const dirty=JSON.stringify(draft)!==JSON.stringify(initial);
  const save=async()=>{
    if(lock.current)return;lock.current=true;setBusy(true);setFailure(null);
    try {
      const price=draft.price.replace(',','.');
      if(!/^\d+(?:\.\d{1,2})?$/.test(price))throw new Error(txt('Introduza um preço válido com até 2 decimais.','Enter a valid price with at most 2 decimals.','Saisissez un prix valide avec au plus 2 décimales.', "Introduzca un precio válido con un máximo de 2 decimales."));
      const response=await fetch('/api/admin/treatments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,keywords:draft.keywords.split('\n').map(s=>s.trim()).filter(Boolean),durationMinutes:Number(draft.duration),priceCents:Math.round(Number(price)*100),version:treatment?.version??0,revision:config.revision})});
      const data=await response.json();
      if(!response.ok){setFailure({message:data.error,code:data.code,conflicts:data.conflicts});return;}
      await onSaved();
    }catch(e){setFailure({message:(e as Error).message});}
    finally {lock.current=false;setBusy(false);}
  };
  const slugify=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100);
  return <EditorDialog title={treatment?txt('Editar tratamento','Edit treatment','Modifier le soin', "Editar tratamiento"):txt('Novo tratamento','New treatment','Nouveau soin', "Nuevo tratamiento")} subtitle={txt('Defina o tratamento, a publicação e os profissionais.','Set treatment details, publication and practitioners.','Définissez le soin, sa publication et ses praticiens.', "Defina los detalles del tratamiento, su publicación y sus profesionales.")} icon={<IconStethoscope size={22}/>} dirty={dirty} busy={busy} onClose={onClose} onSubmit={()=>void save()} submitLabel={txt('Guardar tratamento','Save treatment','Enregistrer le soin', "Guardar tratamiento")} failure={failure} onReload={onReload} lang={lang}>
    <div className="space-y-5">
      <div className="flex gap-2" aria-label={txt('Idioma do conteúdo','Content language','Langue du contenu', "Idioma del contenido")}>{(['pt', 'en', 'fr', 'es'] as const).map(l=><button key={l} type="button" aria-pressed={language===l} className={(language===l?primaryButton:secondaryButton)+' px-3!'} onClick={()=>setLanguage(l)}>{l.toUpperCase()}</button>)}</div>
      <p className="text-xs text-slate-500">{txt('Introduza pelo menos um idioma. As traduções em falta usam o texto disponível.','Enter at least one language. Missing translations use the available text.','Renseignez au moins une langue. Les traductions manquantes utilisent le texte disponible.', "Introduzca al menos un idioma. Las traducciones que falten usarán el texto disponible.")}</p>
      <Field label={txt('Nome','Name','Nom', "Nombre")}><input className={inputClass} maxLength={120} value={draft.name[language]??''} onChange={e=>setDraft({...draft,name:{...draft.name,[language]:e.target.value},...(!treatment&&(!draft.slug||draft.slug===slugify(getLocalizedText(draft.name,language)))?{slug:slugify(e.target.value)}:{})})}/></Field>
      <Field label={txt('Resumo','Summary','Résumé', "Resumen")}><textarea className={inputClass} rows={2} maxLength={400} value={draft.shortDesc[language]??''} onChange={e=>setDraft({...draft,shortDesc:{...draft.shortDesc,[language]:e.target.value}})}/></Field>
      <Field label={txt('Descrição','Description','Description', "Descripción")}><textarea className={inputClass} rows={4} maxLength={6000} value={draft.longDesc[language]??''} onChange={e=>setDraft({...draft,longDesc:{...draft.longDesc,[language]:e.target.value}})}/></Field>
      <Field label={txt('Identificador no endereço do site','Website address identifier','Identifiant de l’adresse du site', "Identificador en la dirección web")} hint={txt('Letras minúsculas, números e hífen. Permanente após a criação.','Lowercase letters, numbers and hyphens. Permanent after creation.','Lettres minuscules, chiffres et tirets. Permanent après création.', "Letras minúsculas, números y guiones. Permanente después de la creación.")}><input className={inputClass} required readOnly={!!treatment} maxLength={100} pattern="[a-z0-9]+(-[a-z0-9]+)*" value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})} onFocus={()=>{if(!draft.slug)setDraft({...draft,slug:slugify(getLocalizedText(draft.name,language))});}}/></Field>
      <div className="grid gap-4 sm:grid-cols-2"><Field label={txt('Categoria','Category','Catégorie', "Categoría")}><select className={inputClass} value={draft.pole} onChange={e=>setDraft({...draft,pole:e.target.value as typeof draft.pole})}><option value="kinesitherapie">{txt('Fisioterapia','Physiotherapy','Kinésithérapie', "Fisioterapia")}</option><option value="minceur">{txt('Estética','Body treatments','Esthétique', "Tratamientos corporales")}</option><option value="bilan">{txt('Avaliação','Assessment','Bilan', "Evaluación")}</option></select></Field><Field label={txt('Publicação','Publication','Publication', "Publicación")}><select className={inputClass} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as TreatmentStatus})}><option value="DRAFT">{txt('Rascunho — oculto','Draft — hidden','Brouillon — masqué', "Borrador — oculto")}</option><option value="PUBLISHED">{txt('Publicado — visível e reservável','Published — visible and bookable','Publié — visible et réservable', "Publicado — visible y reservable")}</option><option value="ARCHIVED">{txt('Arquivado — sem novas marcações','Archived — no new bookings','Archivé — aucune nouvelle réservation', "Archivado — sin nuevas reservas")}</option></select></Field><Field label={txt('Preço (€)','Price (€)','Prix (€)', "Precio (€)")}><input className={inputClass} inputMode="decimal" required value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></Field><Field label={txt('Duração (minutos)','Duration (minutes)','Durée (minutes)', "Duración (minutos)")}><input className={inputClass} type="number" required min={5} max={720} step={1} value={draft.duration} onChange={e=>setDraft({...draft,duration:e.target.value})}/></Field></div>

      <section className="space-y-3">
        <h3 className="text-sm font-semibold">{txt('Pesquisa e mapa do corpo','Discovery and body map','Recherche et carte du corps', "Exploración y mapa corporal")}</h3>
        <p className="text-xs text-slate-500">{txt('Escolha apenas os objetivos e zonas adequados a este tratamento. Sem seleção, aparece em Todos.','Select only the goals and areas appropriate for this treatment. Without a selection, it appears under All.','Choisissez uniquement les objectifs et zones adaptés au soin. Sans sélection, il apparaît dans Tous.', "Seleccione solo los objetivos y las zonas adecuados para este tratamiento. Sin selección, aparecerá en Todos.")}</p>
        <div className="grid gap-4 sm:grid-cols-2">
          <fieldset className="space-y-2"><legend className="mb-2 text-xs font-semibold">{txt('Objetivos','Care goals','Objectifs', "Objetivos del tratamiento")}</legend>{([
            ['posture',txt('Postura e mobilidade','Posture and mobility','Posture et mobilité', "Postura y movilidad")],['slimming',txt('Remodelação','Body contouring','Remodelage', "Remodelado corporal")],['drainage',txt('Drenagem','Drainage','Drainage', "Drenaje")],['postpartum',txt('Pós-parto','Postpartum','Post-partum', "Posparto")]
          ] as const).map(([id,label])=><label key={id} className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={draft.careGoals.includes(id)} onChange={e=>setDraft({...draft,careGoals:e.target.checked?[...draft.careGoals,id]:draft.careGoals.filter(g=>g!==id)})}/>{label}</label>)}</fieldset>
          <fieldset className="space-y-2"><legend className="mb-2 text-xs font-semibold">{txt('Zonas do corpo','Body areas','Zones du corps', "Zonas corporales")}</legend>{([
            ['torso',txt('Tronco','Torso','Tronc', "Torso")],['legs',txt('Pernas','Legs','Jambes', "Piernas")],['arms',txt('Braços','Arms','Bras', "Brazos")],['back',txt('Costas','Back','Dos', "Espalda")]
          ] as const).map(([id,label])=><label key={id} className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={draft.bodyZones.includes(id)} onChange={e=>setDraft({...draft,bodyZones:e.target.checked?[...draft.bodyZones,id]:draft.bodyZones.filter(z=>z!==id)})}/>{label}</label>)}</fieldset>
        </div>
      </section>
      <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold">{txt('Conteúdo clínico e perguntas frequentes','Clinical content and frequently asked questions','Contenu clinique et questions fréquentes', "Contenido clínico y preguntas frecuentes")}</summary><div className="mt-4 space-y-4">
        <p className="text-xs text-slate-500">{txt('Opcional. Uma entrada por linha. O idioma selecionado acima aplica-se a estes campos.','Optional. One entry per line. The content language selected above applies to these fields.','Facultatif. Une entrée par ligne. La langue sélectionnée ci-dessus s’applique à ces champs.', "Opcional. Una entrada por línea. Se aplica a estos campos el idioma de contenido seleccionado arriba.")}</p>
        {([['sessionFlow',txt('Etapas da sessão','Session steps','Étapes de la séance', "Pasos de la sesión")],['indications',txt('Indicações','Indications','Indications', "Indicaciones")],['contraindications',txt('Contraindicações','Contraindications','Contre-indications', "Contraindicaciones")]] as const).map(([key,label])=><Field key={key} label={label}><textarea className={inputClass} rows={3} value={(draft[key][language]??[]).join('\n')} onChange={e=>setDraft({...draft,[key]:{...draft[key],[language]:e.target.value.split('\n')}})}/></Field>)}
        <Field label={txt('Termos de pesquisa','Search terms','Termes de recherche', "Términos de búsqueda")}><textarea className={inputClass} rows={2} value={draft.keywords} onChange={e=>setDraft({...draft,keywords:e.target.value})}/></Field>
        {draft.faq.map((faq,i)=><div key={i} className="space-y-2 rounded-xl border border-slate-200 p-3"><Field label={txt('Pergunta','Question','Question', "Pregunta")+' '+(i+1)}><input className={inputClass} maxLength={300} value={faq.q[language]??''} onChange={e=>setDraft({...draft,faq:draft.faq.map((f,j)=>j===i?{...f,q:{...f.q,[language]:e.target.value}}:f)})}/></Field><Field label={txt('Resposta','Answer','Réponse', "Respuesta")+' '+(i+1)}><textarea className={inputClass} rows={2} maxLength={2000} value={faq.a[language]??''} onChange={e=>setDraft({...draft,faq:draft.faq.map((f,j)=>j===i?{...f,a:{...f.a,[language]:e.target.value}}:f)})}/></Field><button type="button" className={secondaryButton} onClick={()=>setDraft({...draft,faq:draft.faq.filter((_,j)=>j!==i)})}>{txt('Remover pergunta','Remove question','Supprimer la question', "Eliminar pregunta")}</button></div>)}
        <button type="button" className={secondaryButton} disabled={draft.faq.length>=20} onClick={()=>setDraft({...draft,faq:[...draft.faq,{q:{fr:''},a:{fr:''}}]})}>{txt('Adicionar pergunta','Add question','Ajouter une question', "Añadir pregunta")}</button>
      </div></details>
      <section><h3 className="mb-2 text-sm font-semibold">{txt('Profissionais autorizados','Assigned practitioners','Praticiens autorisés', "Profesionales asignados")}</h3><p className="mb-3 text-xs leading-relaxed text-slate-500">{txt('Sem seleção, ninguém pode realizar este tratamento. Para publicar, escolha um profissional ativo, disponível online e com horário. As durações personalizadas definidas na Equipa são mantidas.','With no selection, nobody can provide this treatment. Publishing requires an active practitioner enabled online with working hours. Custom durations set in Team are preserved.','Sans sélection, personne ne peut réaliser ce soin. La publication exige un praticien actif, réservable en ligne et avec des horaires. Les durées personnalisées dans Équipe sont conservées.', "Sin selección, nadie podrá realizar este tratamiento. Para publicarlo se requiere un profesional activo, habilitado para reservas en línea y con horario. Se conservan las duraciones personalizadas de Equipo.")}</p><div className="grid gap-2 sm:grid-cols-2">{config.practitioners.map(p=><label key={p.id} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" className="size-4 accent-blue-600" checked={draft.practitionerIds.includes(p.id)} onChange={e=>setDraft({...draft,practitionerIds:e.target.checked?[...draft.practitionerIds,p.id]:draft.practitionerIds.filter(id=>id!==p.id)})}/><span className="min-w-0 break-words">{p.name}<small className="block text-slate-400">{!p.active?txt('Inativo','Inactive','Inactif', "Inactivo"):!p.bookable?txt('Apenas interno','Internal only','Interne uniquement', "Solo interno"):p.profession}</small></span></label>)}</div>{!config.practitioners.length&&<p className="text-sm text-amber-700">{txt('Crie um profissional no separador Equipa.','Create a practitioner in the Team tab.','Créez un praticien dans l’onglet Équipe.', "Cree un profesional en la pestaña Equipo.")}</p>}</section>
      <p className="rounded-xl bg-blue-50 p-3 text-xs leading-relaxed text-blue-800">{txt('Os novos preços e durações aplicam-se apenas a novas marcações. Arquivar mantém o histórico e as consultas já marcadas.','New prices and durations apply only to new bookings. Archiving keeps history and appointments already booked.','Les nouveaux prix et durées s’appliquent aux nouvelles réservations. L’archivage conserve l’historique et les rendez-vous déjà pris.', "Los nuevos precios y duraciones solo se aplican a nuevas reservas. Al archivar se conservan el historial y las citas ya reservadas.")}</p>
    </div>
  </EditorDialog>;
}
